# FROM node:14
# WORKDIR /client
# COPY package.json yarn.lock ./
# RUN yarn
# COPY . .
# RUN yarn build
# EXPOSE 3000
# CMD ["yarn", "dev"]


#  docker build -t go_react_todos/client .           
# docker run -d -p 8080:8080 go_react_todos/client
# docker run -p 8080:8080 go_react_todos/client
